#!/bin/bash
set -e

function usage
{
    echo "Usage: build <config>";
}

if [ "$#" -ne 1 ];
then
    usage;
    exit 1;
fi

#Process the arguments
for opt in "$@"
do
    case $opt in
    forexai) path="D:\\home\\src\ForexAI\\src\\";;
    misc) path="D:\\home\\src\\misc";;
	eloqua) path="D:\\Dev\\WORKING\\Config\\Development\\IISSetup\\IIS 7.5 Config\\";;
	*) usage ; exit 1 ;;
	esac
done

iisredirection "$path"